"use client";

import { CalendarClock, CalendarDays, ChevronRight, Clock3, MapPin, Plus, Sparkles } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { usePlannr } from "@/components/app-provider";
import { Avatar, Button, EmptyState, Tag } from "@/components/ui";
import { deriveSessionTab, sessionDuration } from "@/lib/session";
import type { PlannedSession, SessionTab } from "@/lib/types";
import { cn, formatSessionDate, minutesLabel } from "@/lib/utils";

const tabs: Array<{ id: SessionTab; label: string }> = [{ id: "upcoming", label: "Upcoming" }, { id: "drafts", label: "Drafts" }, { id: "past", label: "Past" }];

export default function SessionsPage() {
  const { sessions, currentTeam, createSession } = usePlannr(); const [tab, setTab] = useState<SessionTab>("upcoming"); const [creating, setCreating] = useState(false); const router = useRouter();
  const current = useMemo(() => sessions.filter((session) => session.teamId === currentTeam?.id && deriveSessionTab(session) === tab).sort((a, b) => tab === "drafts" ? b.updatedAt.localeCompare(a.updatedAt) : tab === "upcoming" ? (a.startsAt ?? "").localeCompare(b.startsAt ?? "") : (b.startsAt ?? "").localeCompare(a.startsAt ?? "")), [sessions, currentTeam, tab]);
  async function startSession() { setCreating(true); try { const id = await createSession(); router.push(`/sessions/${id}`); } finally { setCreating(false); } }
  if (!currentTeam) return <AppShell><div className="mx-auto max-w-3xl px-4 py-20"><EmptyState icon={<CalendarDays size={22} />} title="Create your first team" body="Sessions belong to a team so the right coaches can see and edit them." action={<Link href="/team" className="inline-flex min-h-11 items-center rounded-xl bg-[var(--orange)] px-4 text-sm font-bold text-white">Set up a team</Link>} /></div></AppShell>;
  return <AppShell><div className="mx-auto max-w-[1260px] px-4 pb-16 pt-7 sm:px-8 sm:pt-10"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[var(--orange)]">{currentTeam?.shortName}</p><h1 className="mt-2 text-4xl font-black tracking-[-.055em] sm:text-5xl">Session library</h1><p className="mt-3 text-[var(--ink-soft)]">Every plan from first thought to final whistle.</p></div><Button size="lg" onClick={() => void startSession()} disabled={creating}><Plus size={19} />{creating ? "Creating…" : "Create session"}</Button></header>
    <div className="mt-10 flex gap-1 overflow-x-auto rounded-2xl border border-[var(--line)] bg-[var(--paper-deep)] p-1.5 sm:w-fit">{tabs.map((entry) => { const count = sessions.filter((session) => session.teamId === currentTeam?.id && deriveSessionTab(session) === entry.id).length; return <button key={entry.id} onClick={() => setTab(entry.id)} className={cn("inline-flex min-h-10 shrink-0 items-center gap-2 rounded-xl px-4 text-sm font-bold text-[var(--ink-soft)] transition", tab === entry.id && "bg-[var(--surface)] text-[var(--ink)] shadow-sm")}>{entry.label}<span className={cn("rounded-full px-2 py-0.5 text-[10px]", tab === entry.id ? "bg-[var(--ink)] text-white" : "bg-black/5")}>{count}</span></button>; })}</div>
    {current.length ? <div className="mt-7 grid gap-4 xl:grid-cols-2">{current.map((session) => <SessionCard key={session.id} session={session} tab={tab} />)}</div> : <div className="mt-7"><EmptyState icon={tab === "drafts" ? <Sparkles size={22} /> : <CalendarDays size={22} />} title={tab === "drafts" ? "No sessions being planned" : tab === "upcoming" ? "Nothing scheduled yet" : "No past sessions"} body={tab === "drafts" ? "Start a plan and invite your coaching team into the details." : tab === "upcoming" ? "Publish a draft and it will appear here automatically." : "Completed sessions will collect here for reference."} action={tab !== "past" ? <Button onClick={() => void startSession()}><Plus size={17} />Create session</Button> : undefined} /></div>}
  </div></AppShell>;
}

function SessionCard({ session, tab }: { session: PlannedSession; tab: SessionTab }) {
  const { currentTeam } = usePlannr(); const built = sessionDuration(session); const progress = session.plannedDurationMinutes ? Math.min(100, Math.round((built / session.plannedDurationMinutes) * 100)) : 0; const updater = currentTeam?.members.find((member) => member.id === session.updatedBy) ?? currentTeam?.members[0];
  return <Link href={`/sessions/${session.id}`} className="group rounded-[24px] border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[0_8px_30px_rgba(16,32,29,.04)] transition hover:-translate-y-0.5 hover:border-[#b7b2a6] hover:shadow-[var(--shadow)] sm:p-6"><div className="flex items-start justify-between gap-4"><Tag tone={tab === "drafts" ? "orange" : tab === "upcoming" ? "green" : "neutral"}>{tab === "drafts" ? "Draft" : tab === "upcoming" ? "Scheduled" : "Completed"}</Tag><ChevronRight className="text-[var(--ink-soft)] transition group-hover:translate-x-1 group-hover:text-[var(--orange)]" size={20} /></div><h2 className="mt-5 text-2xl font-black tracking-[-.04em]">{session.title}</h2><div className="mt-4 grid gap-2 text-sm text-[var(--ink-soft)] sm:grid-cols-2"><span className="flex items-center gap-2"><CalendarClock size={16} />{formatSessionDate(session.startsAt)}</span><span className="flex items-center gap-2"><MapPin size={16} />{session.venue || "Venue not set"}</span><span className="flex items-center gap-2"><Clock3 size={16} />{minutesLabel(session.plannedDurationMinutes)} planned</span><span className="flex items-center gap-2"><CalendarDays size={16} />{session.blocks.length} {session.blocks.length === 1 ? "block" : "blocks"}</span></div>{tab === "drafts" && <div className="mt-6"><div className="mb-2 flex justify-between text-xs font-bold"><span>{built} of {session.plannedDurationMinutes} minutes built</span><span>{progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[var(--paper-deep)]"><div className="h-full rounded-full bg-[var(--orange)] transition-all" style={{ width: `${progress}%` }} /></div></div>}<div className="mt-6 flex items-center gap-2 border-t border-[var(--line)] pt-4 text-xs font-semibold text-[var(--ink-soft)]">{updater && <Avatar name={updater.fullName} initials={updater.initials} color={updater.color} size="sm" />}<span>{tab === "drafts" ? `Last edited by ${updater?.fullName ?? "a coach"}` : session.objective || "Open the session plan"}</span></div></Link>;
}
