"use client";
/* eslint-disable @next/next/no-img-element -- session thumbnails snapshot arbitrary library media */

import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { ArrowLeft, BookOpen, Calendar, Check, ChevronDown, Clock3, GripVertical, Library, MapPin, MoreVertical, Plus, Radio, Search, Sparkles, Trash2, UserRoundPlus, WifiOff } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { AppShell } from "./app-shell";
import { usePlannr } from "./app-provider";
import { ExerciseThumbnail } from "./exercise-thumbnail";
import { Avatar, Button, EmptyState, Field, inputClass, Modal, Tag, textareaClass } from "./ui";
import { useSessionRealtime } from "@/hooks/use-session-realtime";
import { blockDuration, sessionDuration, validatePublish } from "@/lib/session";
import type { PlannedSession, SessionBlock, SessionItem } from "@/lib/types";
import { cn, minutesLabel, toDateTimeLocal } from "@/lib/utils";

const blockPresets = ["Warm-up", "Main block", "Game", "Cool-down"];

export function SessionBuilder({ sessionId }: { sessionId: string }) {
  const store = usePlannr(); const router = useRouter(); const session = store.sessions.find((entry) => entry.id === sessionId); const [activeBlockId, setActiveBlockId] = useState<string | null>(session?.blocks[0]?.id ?? null); const [blockMenu, setBlockMenu] = useState(false); const [pickerBlock, setPickerBlock] = useState<string | null>(null); const [publishIssues, setPublishIssues] = useState<string[]>([]); const [publishing, setPublishing] = useState(false);
  const { collaborators, connected } = useSessionRealtime(sessionId, store.user, activeBlockId, () => store.reloadSession(sessionId), store.isDemoMode);
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  if (!session) return <AppShell><div className="mx-auto max-w-3xl px-5 py-20"><EmptyState icon={<Calendar size={23} />} title="Session not found" body="It may have been removed or belong to another team." action={<Link href="/sessions" className="font-bold underline">Back to sessions</Link>} /></div></AppShell>;
  const stableSession = session;
  const builtMinutes = sessionDuration(session); const difference = builtMinutes - session.plannedDurationMinutes;

  async function addBlock(title: string) { const id = await store.addBlock(sessionId, title); setActiveBlockId(id); setBlockMenu(false); }
  async function publish() { const issues = validatePublish(stableSession); if (issues.length) { setPublishIssues(issues); return; } setPublishing(true); try { await store.publishSession(sessionId); } finally { setPublishing(false); } }
  function blocksDragEnd(event: DragEndEvent) { const { active, over } = event; if (!over || active.id === over.id) return; const oldIndex = stableSession.blocks.findIndex((block) => block.id === active.id); const newIndex = stableSession.blocks.findIndex((block) => block.id === over.id); void store.reorderBlocks(sessionId, arrayMove(stableSession.blocks, oldIndex, newIndex).map((block) => block.id)); }

  return <AppShell><div className="min-h-screen pb-24"><header className="sticky top-0 z-20 border-b border-[var(--line)] bg-[var(--paper)]/92 px-4 py-3 backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-[1380px] items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><Link href="/sessions" className="grid h-10 w-10 shrink-0 place-items-center rounded-xl hover:bg-black/5" aria-label="Back to sessions"><ArrowLeft size={20} /></Link><div className="min-w-0"><p className="truncate text-sm font-black">{session.title}</p><div className="mt-0.5 flex items-center gap-2 text-[11px] font-semibold text-[var(--ink-soft)]">{store.saveState === "saving" ? <><span className="h-2 w-2 animate-pulse rounded-full bg-[var(--orange)]" />Saving…</> : store.saveState === "offline" || !connected ? <><WifiOff size={12} />Reconnecting…</> : <><Check size={12} />All changes saved</>}</div></div></div><div className="flex items-center gap-2"><div className="hidden items-center -space-x-2 sm:flex">{collaborators.map((person) => <Avatar key={person.id} {...person} name={person.fullName} />)}{collaborators.length > 0 && <span className="ml-4 text-xs font-bold text-[var(--ink-soft)]">{collaborators.length} editing</span>}</div><Button variant="secondary" className="hidden md:inline-flex"><UserRoundPlus size={17} />Invite coach</Button><Button onClick={() => void publish()} disabled={publishing || session.status === "published"}>{session.status === "published" ? <><Check size={17} />Published</> : publishing ? "Publishing…" : "Publish"}</Button></div></div></header>
    <div className="mx-auto grid max-w-[1380px] gap-7 px-4 pt-7 sm:px-7 xl:grid-cols-[minmax(0,1fr)_330px]"><main className="min-w-0"><section className="rounded-[26px] border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[0_8px_30px_rgba(16,32,29,.04)] sm:p-7"><div className="flex items-center justify-between gap-3"><div><Tag tone={session.status === "draft" ? "orange" : "green"}>{session.status === "draft" ? "Draft session" : "Published"}</Tag><AutoField className="mt-3 text-3xl font-black tracking-[-.045em] sm:text-4xl" value={session.title} onSave={(value) => store.updateSession(sessionId, { title: value })} ariaLabel="Session title" /></div><MoreVertical className="text-[var(--ink-soft)]" size={20} /></div><div className="mt-7 grid gap-5 border-t border-[var(--line)] pt-6 sm:grid-cols-2"><Field label="Date & time"><div className="relative"><Calendar className="absolute left-3.5 top-3.5 text-[var(--ink-soft)]" size={17} /><input type="datetime-local" className={`${inputClass} pl-10`} value={toDateTimeLocal(session.startsAt)} onChange={(event) => void store.updateSession(sessionId, { startsAt: event.target.value ? new Date(event.target.value).toISOString() : null })} /></div></Field><Field label="Venue"><div className="relative"><MapPin className="absolute left-3.5 top-3.5 text-[var(--ink-soft)]" size={17} /><DebouncedInput className={`${inputClass} pl-10`} value={session.venue} placeholder="Court or venue" onSave={(value) => store.updateSession(sessionId, { venue: value })} /></div></Field><Field label="Planned duration"><div className="relative"><Clock3 className="absolute left-3.5 top-3.5 text-[var(--ink-soft)]" size={17} /><select className={`${inputClass} appearance-none pl-10`} value={session.plannedDurationMinutes} onChange={(event) => void store.updateSession(sessionId, { plannedDurationMinutes: Number(event.target.value) })}>{[45, 60, 75, 90, 105, 120].map((minutes) => <option key={minutes} value={minutes}>{minutesLabel(minutes)}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3.5 top-3.5 text-[var(--ink-soft)]" size={17} /></div></Field><Field label="Session objective"><DebouncedInput className={inputClass} value={session.objective} placeholder="What should the team improve?" onSave={(value) => store.updateSession(sessionId, { objective: value })} /></Field></div></section>
      <section className="mt-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[var(--orange)]">Session timeline</p><h2 className="mt-2 text-3xl font-black tracking-[-.045em]">Build the work</h2></div><div className="relative"><Button variant="secondary" onClick={() => setBlockMenu((value) => !value)}><Plus size={18} />Add block<ChevronDown size={16} /></Button>{blockMenu && <div className="absolute right-0 top-13 z-10 w-48 rounded-2xl border border-[var(--line)] bg-white p-2 shadow-xl">{blockPresets.map((preset) => <button key={preset} onClick={() => void addBlock(preset)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold hover:bg-black/5">{preset}</button>)}<button onClick={() => { const title = prompt("Block name", "Custom block"); if (title?.trim()) void addBlock(title.trim()); }} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-[var(--orange)] hover:bg-[#fff0e8]">Custom block…</button></div>}</div></div>
        {session.blocks.length ? <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={blocksDragEnd}><SortableContext items={session.blocks.map((block) => block.id)} strategy={verticalListSortingStrategy}><div className="mt-6 grid gap-5">{session.blocks.map((block, index) => <SortableBlockCard key={block.id} block={block} index={index} session={session} active={activeBlockId === block.id} collaborators={collaborators.filter((person) => person.activeBlockId === block.id)} onActive={() => setActiveBlockId(block.id)} onPickExercise={() => setPickerBlock(block.id)} />)}</div></SortableContext></DndContext> : <div className="mt-6"><EmptyState icon={<Sparkles size={22} />} title="Start with a block" body="Add a warm-up, main block, game or your own custom section." action={<Button onClick={() => void addBlock("Warm-up")}><Plus size={17} />Add warm-up</Button>} /></div>}
      </section></main>
      <aside className="space-y-5 xl:sticky xl:top-24 xl:self-start"><section className="rounded-[24px] bg-[var(--ink)] p-5 text-white shadow-[var(--shadow)]"><p className="text-xs font-black uppercase tracking-[.14em] text-white/45">Time check</p><div className="mt-4 flex items-baseline gap-2"><strong className="text-4xl font-black tracking-[-.06em]">{builtMinutes}</strong><span className="text-white/55">of {session.plannedDurationMinutes} min</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className={cn("h-full rounded-full", difference > 0 ? "bg-[var(--orange)]" : "bg-[var(--lime)]")} style={{ width: `${Math.min(100, Math.round((builtMinutes / session.plannedDurationMinutes) * 100))}%` }} /></div><p className="mt-3 text-xs leading-5 text-white/55">{difference === 0 ? "Your timeline matches the planned duration." : difference > 0 ? `${difference} minutes over the planned time.` : `${Math.abs(difference)} minutes still available.`}</p></section><section className="rounded-[24px] border border-[var(--line)] bg-[var(--surface)] p-5"><div className="flex items-center justify-between"><h3 className="font-black">Live collaborators</h3><span className="flex items-center gap-1.5 text-xs font-bold text-[#34745f]"><Radio size={13} className="animate-pulse" />Live</span></div><div className="mt-4 grid gap-3">{collaborators.map((person) => { const block = session.blocks.find((entry) => entry.id === person.activeBlockId); return <div key={person.id} className="flex items-center gap-3"><Avatar name={person.fullName} initials={person.initials} color={person.color} /><div><p className="text-sm font-bold">{person.fullName}</p><p className="text-xs text-[var(--ink-soft)]">{block ? `Editing ${block.title}` : "Viewing session"}</p></div></div>; })}{!collaborators.length && <p className="text-sm leading-6 text-[var(--ink-soft)]">You’re the only coach here right now.</p>}</div></section><section className="rounded-[24px] border border-[var(--line)] bg-[var(--surface)] p-5"><h3 className="font-black">General notes</h3><DebouncedTextarea className={`${textareaClass} mt-3 min-h-36`} value={session.notes} placeholder="Equipment, player availability or reminders…" onSave={(value) => store.updateSession(sessionId, { notes: value })} /></section><Button variant="danger" className="w-full" onClick={() => { if (confirm("Delete this session? This cannot be undone.")) void store.deleteSession(sessionId).then(() => router.push("/sessions")); }}><Trash2 size={17} />Delete session</Button></aside></div>
    <ExercisePicker open={Boolean(pickerBlock)} blockId={pickerBlock} onClose={() => setPickerBlock(null)} sessionId={sessionId} />
    <Modal open={publishIssues.length > 0} onClose={() => setPublishIssues([])} title="A few details are missing" description="Complete these before the session is shared with your team."><ul className="grid gap-3">{publishIssues.map((issue) => <li key={issue} className="flex items-center gap-3 rounded-xl bg-[var(--paper)] px-4 py-3 text-sm font-bold"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#fde1d5] text-xs text-[#9c3913]">!</span>{issue}</li>)}</ul><div className="mt-6 flex justify-end"><Button onClick={() => setPublishIssues([])}>Keep planning</Button></div></Modal>
  </div></AppShell>;
}

function SortableBlockCard({ block, index, session, active, collaborators, onActive, onPickExercise }: { block: SessionBlock; index: number; session: PlannedSession; active: boolean; collaborators: ReturnType<typeof useSessionRealtime>["collaborators"]; onActive(): void; onPickExercise(): void }) {
  const store = usePlannr(); const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: block.id }); const itemSensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  function itemDragEnd(event: DragEndEvent) { if (!event.over || event.active.id === event.over.id) return; const oldIndex = block.items.findIndex((item) => item.id === event.active.id); const newIndex = block.items.findIndex((item) => item.id === event.over?.id); void store.reorderItems(session.id, block.id, arrayMove(block.items, oldIndex, newIndex).map((item) => item.id)); }
  return <article ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition, opacity: isDragging ? .6 : 1 }} onPointerDown={onActive} className={cn("rounded-[24px] border bg-[var(--surface)] shadow-[0_7px_24px_rgba(16,32,29,.04)] transition", active ? "border-[#9bb8ad] ring-4 ring-[#bfe0cf]/35" : "border-[var(--line)]")}><header className="flex items-center gap-3 border-b border-[var(--line)] p-4 sm:px-5"><button {...attributes} {...listeners} className="grid h-9 w-8 shrink-0 place-items-center rounded-lg text-[var(--ink-soft)] hover:bg-black/5" aria-label={`Drag ${block.title}`}><GripVertical size={19} /></button><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-[var(--paper-deep)] text-xs font-black">{index + 1}</span><AutoField className="min-w-0 flex-1 text-lg font-black" value={block.title} onSave={(value) => store.updateBlock(session.id, block.id, value)} ariaLabel="Block title" />{collaborators.map((person) => <Avatar key={person.id} name={person.fullName} initials={person.initials} color={person.color} size="sm" />)}<span className="shrink-0 rounded-full bg-black/5 px-2.5 py-1 text-xs font-black">{blockDuration(block)} min</span><Button variant="ghost" size="sm" className="px-2" aria-label={`Delete ${block.title}`} onClick={() => { if (confirm(`Delete ${block.title}?`)) void store.deleteBlock(session.id, block.id); }}><Trash2 size={16} /></Button></header><div className="p-3 sm:p-4">{block.items.length ? <DndContext sensors={itemSensors} collisionDetection={closestCenter} onDragEnd={itemDragEnd}><SortableContext items={block.items.map((item) => item.id)} strategy={verticalListSortingStrategy}><div className="grid gap-2.5">{block.items.map((item) => <SortableItemCard key={item.id} item={item} block={block} session={session} />)}</div></SortableContext></DndContext> : <p className="py-6 text-center text-sm text-[var(--ink-soft)]">No activities in this block yet.</p>}<div className="mt-3 grid grid-cols-2 gap-2"><Button variant="secondary" size="sm" onClick={onPickExercise}><Library size={16} />Add exercise</Button><Button variant="ghost" size="sm" onClick={() => void store.addCustomItem(session.id, block.id)}><Plus size={16} />Custom activity</Button></div></div></article>;
}

function SortableItemCard({ item, block, session }: { item: SessionItem; block: SessionBlock; session: PlannedSession }) {
  const store = usePlannr(); const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: item.id });
  return <div ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition, opacity: isDragging ? .65 : 1 }} className="grid grid-cols-[32px_minmax(0,1fr)_70px_36px] items-start gap-2 rounded-2xl border border-[var(--line)] bg-white p-2.5 sm:grid-cols-[32px_54px_minmax(0,1fr)_84px_36px]"><button {...attributes} {...listeners} className="grid h-10 place-items-center text-[var(--ink-soft)]" aria-label={`Drag ${item.title}`}><GripVertical size={17} /></button>{item.thumbnailUrl ? <img src={item.thumbnailUrl} alt="" className="hidden h-12 w-12 rounded-xl object-cover sm:block" /> : <span className="hidden h-12 w-12 place-items-center rounded-xl bg-[var(--paper-deep)] sm:grid">{item.kind === "exercise" ? <BookOpen size={17} /> : <Sparkles size={17} />}</span>}<div className="min-w-0"><DebouncedInput className="h-8 w-full rounded-lg border-0 bg-transparent px-1 text-sm font-black outline-none focus:bg-[var(--paper)]" value={item.title} onSave={(value) => store.updateItem(session.id, block.id, item.id, { title: value })} /><DebouncedInput className="h-7 w-full truncate rounded-lg border-0 bg-transparent px-1 text-xs text-[var(--ink-soft)] outline-none focus:bg-[var(--paper)]" value={item.coachingNotes} placeholder="Add coaching note…" onSave={(value) => store.updateItem(session.id, block.id, item.id, { coachingNotes: value })} /></div><label className="relative"><input type="number" min="1" max="180" className="h-10 w-full rounded-xl border border-[var(--line)] bg-[var(--paper)] px-2 pr-7 text-right text-sm font-black outline-none" value={item.durationMinutes} onChange={(event) => void store.updateItem(session.id, block.id, item.id, { durationMinutes: Math.max(1, Number(event.target.value)) })} aria-label={`Duration for ${item.title}`} /><span className="pointer-events-none absolute right-2 top-3 text-[10px] font-bold text-[var(--ink-soft)]">m</span></label><Button variant="ghost" size="sm" className="px-2" aria-label={`Remove ${item.title}`} onClick={() => void store.deleteItem(session.id, block.id, item.id)}><Trash2 size={15} /></Button></div>;
}

function ExercisePicker({ open, blockId, sessionId, onClose }: { open: boolean; blockId: string | null; sessionId: string; onClose(): void }) {
  const { exercises, addExerciseItem } = usePlannr(); const [query, setQuery] = useState(""); const filtered = useMemo(() => exercises.filter((exercise) => `${exercise.name} ${exercise.description}`.toLowerCase().includes(query.toLowerCase())), [exercises, query]);
  return <Modal open={open} onClose={onClose} title="Add from exercise library" description="Exercise details are copied into this session, so the plan stays stable." size="lg"><div className="relative"><Search className="absolute left-3.5 top-3.5 text-[var(--ink-soft)]" size={18} /><input className={`${inputClass} pl-10`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search exercises…" autoFocus /></div><div className="mt-5 grid max-h-[55vh] gap-3 overflow-y-auto pr-1 thin-scrollbar sm:grid-cols-2">{filtered.map((exercise) => <button key={exercise.id} className="group flex gap-3 rounded-2xl border border-[var(--line)] bg-white p-3 text-left transition hover:border-[var(--ink)]" onClick={() => { if (blockId) void addExerciseItem(sessionId, blockId, exercise); onClose(); }}><ExerciseThumbnail exercise={exercise} className="h-20 w-24 shrink-0 rounded-xl" /><span className="min-w-0"><strong className="block text-sm">{exercise.name}</strong><span className="clamp-2 mt-1 text-xs leading-5 text-[var(--ink-soft)]">{exercise.description}</span></span></button>)}</div></Modal>;
}

function AutoField({ value, onSave, className, ariaLabel }: { value: string; onSave(value: string): Promise<void>; className?: string; ariaLabel: string }) {
  return <DebouncedInput value={value} onSave={onSave} aria-label={ariaLabel} className={cn("w-full rounded-lg border-0 bg-transparent px-1 outline-none focus:bg-[var(--paper)]", className)} />;
}
function DebouncedInput({ value, onSave, ...props }: Omit<React.InputHTMLAttributes<HTMLInputElement>, "value" | "onChange"> & { value: string; onSave(value: string): Promise<void> }) {
  const [local, setLocal] = useState(value); const saveRef = useRef(onSave);
  useEffect(() => { saveRef.current = onSave; }, [onSave]);
  useEffect(() => { const timer = window.setTimeout(() => setLocal(value), 0); return () => window.clearTimeout(timer); }, [value]);
  useEffect(() => { if (local === value) return; const timer = window.setTimeout(() => void saveRef.current(local), 550); return () => window.clearTimeout(timer); }, [local, value]);
  return <input {...props} value={local} onChange={(event) => setLocal(event.target.value)} />;
}
function DebouncedTextarea({ value, onSave, ...props }: Omit<React.TextareaHTMLAttributes<HTMLTextAreaElement>, "value" | "onChange"> & { value: string; onSave(value: string): Promise<void> }) {
  const [local, setLocal] = useState(value); const saveRef = useRef(onSave);
  useEffect(() => { saveRef.current = onSave; }, [onSave]);
  useEffect(() => { const timer = window.setTimeout(() => setLocal(value), 0); return () => window.clearTimeout(timer); }, [value]);
  useEffect(() => { if (local === value) return; const timer = window.setTimeout(() => void saveRef.current(local), 550); return () => window.clearTimeout(timer); }, [local, value]);
  return <textarea {...props} value={local} onChange={(event) => setLocal(event.target.value)} />;
}
